### ISSUE TITLE
Extreme server lag when mass is spammed.

### ISSUE THREAD

**Issue by darknight99x** [ItzLevvie/Cigar#12]
I have been getting decent traffic lately, and players seem to have wanted to spam W at the corners of the map.

I have Jxcore installed and everything and I can't seem to get the lag to stop.

Is there anyway you can disable physics or have a timeout of when W mass disappears?
Thanks.

**Comment by darknight99x** [comment]
@ItzLevvie can I have a reason why they were closed? Haha <3

**Comment by ItzLevvie** [comment]
A new branch will be coming shortly.

**Comment by darknight99x** [comment]
Okay thanks @ItzLevvie
