### ISSUE TITLE
jxcore one CPU & memory leak

### ISSUE THREAD

**Issue by volkovmqx** [ItzLevvie/Cigar#18]
Hello,
i am using your Cigar Version with jxcore. it seems to only run on one CPU Core. 
Also, even with the GC, there is a huge memory leak (8Gb is filled in 24h) and when the memory > 50% (4Gb) there is a huge lag.

any solution to this ?
Thanks

**Comment by ItzLevvie** [comment]
Will be fixed when we move on to MultiOgar, wait for a new build coming in Saturday or Sunday.

**Comment by ElMay0r** [comment]
Lag would be fixed?

**Comment by ItzLevvie** [comment]
Yes.
