### ISSUE TITLE
Minimum ram?

### ISSUE THREAD

**Issue by Conor219** [ItzLevvie/Cigar#23]
Hi programmers, a question.
How much RAM is needed at least for a server with 40 or 50 players?

**Comment by volkovmqx** [comment]
from my experience, not too much, 2GB should be enough for 48h without restart (not much memory leak).
 but ! it need a lot of CPU and , since nodeJS is single Core, you need a fast CPU on a dedicated server. VPS are rubbish.

**Comment by Conor219** [comment]
What do you think of using jx?

**Comment by volkovmqx** [comment]
well, maybe the GC is working better with JX, but node and JX "are the same" toward CPU strategy, and only one core is working (i have tested this)

**Comment by eevaqueen** [comment]
@Conor219 
2GB ram for 100 player restart time every 12h,so 1Gb will be good for 50 player.
