### ISSUE TITLE
How do compatible splitspeed

### ISSUE THREAD

**Issue by RelTakeover** [ItzLevvie/Cigar#24]
HOW DO COMPATIBLE ?

on gameserver.js

 // Create cell
    var newCell = new Entity.PlayerCell(this.getNextNodeId(), client, newPos, mass, this);
    newCell.setAngle(angle);
    newCell.setMoveEngineData(SplitSpeed, 32, 0.87); // CIGAR CONFIGURATION

for something as: 

 var splitSpeed = gameServer.config.splitSpeed + (split.getSpeed() * 3 / 2) * Math.max(Math.log10(newMass) - 2.2, 1);
   if (cell.mass <= 10) {
     split.setMoveEngineData(85, 32, 0.85);
   } else 
   if (cell.mass <= 610) {
       split.setMoveEngineData(87, 32, 0.85);
   } else 
   if (cell.mass <= 5000) {
   split.setMoveEngineData(99, 32, 0.90);
   } else 
   if (cell.mass <= 10000) {
     split.setMoveEngineData(105, 32, 0.91);
   } else 
   if (cell.mass <= 20000) {
     split.setMoveEngineData(109, 32, 0.92);
   } else 
 split.setMoveEngineData(splitSpeed, 32, 0.85); //vanilla agar.io = 130, 32, 0.85

**Comment by MastaCoder** [comment]
?

**Comment by RelTakeover** [comment]
Putting a space exact speed between those ranges Size
