### ISSUE TITLE
where is new build?

### ISSUE THREAD

**Issue by darknight99x** [ItzLevvie/Cigar#25]
you said last weekend. something go wrong?

**Comment by MastaCoder** [comment]
What do you mean?

**Comment by darknight99x** [comment]
@MastaCoder they said a new build of this was coming, implementing MultiOgar, better performance

**Comment by ItzLevvie** [comment]
I will make a quick build tommorow and then fix bugs later.

**Comment by ItzLevvie** [comment]
Also sorry about the delay, had to deal with school

**Comment by darknight99x** [comment]
@ItzLevvie Totally fine, as long as you guys plan to keep updating this, I don't care how long it takes. <3

**Comment by darknight99x** [comment]
@ItzLevvie Um...
