### ISSUE TITLE
Multithread, agario.city.

### ISSUE THREAD

**Issue by CalvinDKHD** [ItzLevvie/Cigar#26]
Hey i was in contact with the owner of agario.city which uses levvies version of cigar!
his is multithreaded. He said he was using node.

I found this link / https://www.npmjs.com/package/threads
is it useful?

And he also has a minimap, here is the files for it - https://www.mediafire.com/?vh05btu8969izsg

**Comment by ItzLevvie** [comment]
use pm2 module
