### ISSUE TITLE
UpdateNodes.js more updated?

### ISSUE THREAD

**Issue by Conor219** [ItzLevvie/Cigar#28]
Hi programmers,
Someone has UpdateNode.js for a more updated client?
My client: Agareoz.com
The current UpdateNode.js is not compatible with my client.
I am looking forward to your response.

**Comment by MastaCoder** [comment]
The protocol from MultiOgar seems to work the best, try pulling code from the protocol you want.

**Comment by Conor219** [comment]
I do not like Multihogar, you have very ugly spaces.
And I would like to ItzLevvie server for FFA my server, but the version of UpdateNodes.js prevents me.
@MastaCoder could you help me?

**Comment by MastaCoder** [comment]
Ugly spaces? You mean splits?

**Comment by Conor219** [comment]
Yah, splits ugly :/

**Comment by MastaCoder** [comment]
Can't you just copy the protocol code?

**Comment by Conor219** [comment]
No, new protocols do not work with this server,
Try you, and then you tell me that such.
