### ISSUE TITLE
Shadow in letters

### ISSUE THREAD

**Issue by Conor219** [ItzLevvie/Cigar#3]
Hi itzLevvie, a question.
As you know, the new update Agario, the shadow of the letters is thicker. How do you get that?
It is configured on the server or in client?

I expect an answer, greetings :)

**Comment by ItzLevvie** [comment]
should be somewhere in main_out?

**Comment by Conor219** [comment]
I can't find where to set its opacity. :C

**Comment by darknight99x** [comment]
I would like to know this too @ItzLevvie

**Comment by darknight99x** [comment]
Conor219. I found it in main_out.js

Do CTRL-F

And look for lineWidth.
