### ISSUE TITLE
Bigger map = lag Help!!

### ISSUE THREAD

**Issue by eevaqueen** [ItzLevvie/Cigar#31]
Hello,
I have strange problem when i make border 20k in orginal Cigar it is ok and cpu state is 50%,but in this ItzLevvie/Cigar when i make border 20k cpu state hit up to 90%,so i make border smaller but the map with 14k is very small?,please anyone can help me with that?.
Thanks.

**Comment by MastaCoder** [comment]
It's due to the poor build of the physics. I would wait until the MultiOgar build is released.
