### ISSUE TITLE
JXCore Help

### ISSUE THREAD

**Issue by CalvinDKHD** [ItzLevvie/Cigar#6]
Levvie, hey its Calvin. Umm How do i install JXCore, the server is on CentOS. But isnt there any files i need to replace in the node modules?
Or just uninstall node and install jxcore.

**Comment by darknight99x** [comment]
I've been trying to look this up for a while now, I can't seem to find an installation that properly works for nodejs. I have Windows and I have no clue on how to compile it or anything :-1:

**Comment by CalvinDKHD** [comment]
I found out, install JXCore and in the start file, change node to jx instead.

**Comment by darknight99x** [comment]
Ah well that's for ubuntu, i cant get the windows batch file to work.
